### ISSUE TITLE
Update the styles of all the built-in command consoles

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony#14138]
Now that #14057 has been merged, we need to update the styles of all the built-in console commands. Let's make a list to coordinate the work:

  * [x] assetic:dump (https://github.com/symfony/assetic-bundle/pull/387)
  * [x] assetic:watch (https://github.com/symfony/assetic-bundle/pull/387)
  * [x] assets:install (https://github.com/symfony/symfony/pull/14235)
  * [x] cache:clear (https://github.com/symfony/symfony/pull/15978)
  * [x] cache:warmup (https://github.com/symfony/symfony/pull/15978)
  * [x] config:debug (https://github.com/symfony/symfony/pull/15980)
  * [x] config:dump-reference (https://github.com/symfony/symfony/pull/15980)
  * [x] container:debug (https://github.com/symfony/symfony/pull/15983)
  * [x] debug:config (https://github.com/symfony/symfony/pull/15980)
  * [x] debug:container (https://github.com/symfony/symfony/pull/15983)
  * [x] debug:event-dispatcher (https://github.com/symfony/symfony/pull/15999)
  * [x] debug:router (done in #14132)
  * [x] debug:swiftmailer (https://github.com/symfony/swiftmailer-bundle/pull/115)
  * [x] debug:translation (done in #14595)
  * [x] debug:twig (https://github.com/symfony/symfony/pull/15989)
  * [ ] generate:bundle
  * [ ] generate:controller
  * [x] router:debug (done in #14132)
  * [x] router:dump-apache (done in #14132)
  * [x] router:match (done in #14132)
  * [x] security:check (https://github.com/sensiolabs/security-checker/pull/54)
  * [x] security:encode-password (done in #14032)
  * [x] server:run (https://github.com/symfony/symfony/pull/15972)
  * [x] server:start (https://github.com/symfony/symfony/pull/15972)
  * [x] server:status (https://github.com/symfony/symfony/pull/15972)
  * [x] server:stop (https://github.com/symfony/symfony/pull/15972)
  * [x] swiftmailer:debug (https://github.com/symfony/swiftmailer-bundle/pull/115)
  * [x] swiftmailer:email:send (https://github.com/symfony/swiftmailer-bundle/pull/115)
  * [x] swiftmailer:spool:send (https://github.com/symfony/swiftmailer-bundle/pull/115)
  * [x] translation:debug (done in #14595)
  * [x] translation:update (done in #14595)
  * [x] twig:debug (https://github.com/symfony/symfony/pull/15989)
  * [x] twig:lint (https://github.com/symfony/symfony/pull/15989)
  * [x] yaml:lint (https://github.com/symfony/symfony/pull/15991)

### Commands that will be redesigned later

  * [ ] doctrine:cache:clear-metadata
  * [ ] doctrine:cache:clear-query
  * [ ] doctrine:cache:clear-result
  * [ ] doctrine:database:create
  * [ ] doctrine:database:drop
  * [ ] doctrine:ensure-production-settings
  * [ ] doctrine:fixtures:load
  * [ ] doctrine:generate:crud
  * [ ] doctrine:generate:entities
  * [ ] doctrine:generate:entity
  * [ ] doctrine:generate:form
  * [ ] doctrine:mapping:convert
  * [ ] doctrine:mapping:import
  * [ ] doctrine:mapping:info
  * [ ] doctrine:query:dql
  * [ ] doctrine:query:sql
  * [ ] doctrine:schema:create
  * [ ] doctrine:schema:drop
  * [ ] doctrine:schema:update
  * [ ] doctrine:schema:validate
  * [ ] generate:doctrine:crud
  * [ ] generate:doctrine:entities
  * [ ] generate:doctrine:entity
  * [ ] generate:doctrine:form
  * [ ] orm:convert:mapping

### Deprecated commands which won't be updated

  * [x] init:acl

**Comment by 1ed** [comment]
I created a PR for `assets:install` #14235

**Comment by stof** [comment]
The list you gave here contains lots of commands which are not in the core but in other bundles

**Comment by javiereguiluz** [comment]
That's right. But this is a meta-issue to simplify tracking which commands are updated and which not.

**Comment by javiereguiluz** [comment]
I'm closing this issue as fixed. All Symfony commands have been updated and the remaining Doctrine commands will be updated in a separate pull request (and some of them in the Doctrine repository).
