### ISSUE TITLE
Dual PSR-7 + HttpFoundation support on a component by component basis

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#15414]
Naïve list gathered with grep. Let's make using each of these usable, standalone, in a PSR-7 centric app, or just check if there is something to do, or decide to not do it.

## May handle PSR-7:

- [x] Bridge/Doctrine (see https://github.com/symfony/symfony/issues/15414#issuecomment-126414399)
- [ ] Bridge/Monolog
- [x] Bridge/Swiftmailer (see https://github.com/symfony/symfony/issues/15414#issuecomment-126696544)
- [ ] Bridge/Twig
- [ ] Component/Asset
- [x] Component/Debug (see #15415 and #15418)
- [ ] Component/Form
- [ ] Component/Routing
- [ ] Component/Security/Core
- [x] Component/Security/Csrf (see https://github.com/symfony/symfony/issues/15414#issuecomment-126429803)
- [ ] Component/Security/Http
- [x] Component/Translation (see https://github.com/symfony/symfony/issues/15414#issuecomment-126698024)
- [x] Component/Validator (see #15421)

## May not handle PSR-7:

- [ ] Component/HttpFoundation
- [ ] Component/HttpKernel
- [ ] Bundle/DebugBundle
- [ ] Bundle/FrameworkBundle
- [ ] Bundle/SecurityBundle
- [ ] Bundle/TwigBundle
- [ ] Bundle/WebProfilerBundle

**Comment by stof** [comment]
PSR-7 support for Monolog and Switfmailer should maybe live outside the bridge, in libraries themselves, depending of what relies on HttpFoundation in them.

The Doctrine bridge only relies on HttpFoundation for its Session part, which is out of the scope of PSR-7. The other place using HttpFoundation is the DataCollector, but changing this is a matter of refactoring the profiler, not of refactoring the bridge. So I'm marking the Doctrine bridge as covered.

**Comment by stof** [comment]
btw, many places are relying on the RequestStack to access the Request. But we don't have a RequestStack equivalent based on PSR-7

**Comment by WouterJ** [comment]
Routing has its own issue for PSR-7: https://github.com/symfony/symfony/issues/14723

**Comment by WouterJ** [comment]
Security Core 2.8 will have only one usage of Request in the [`ExpressionVoter`](https://github.com/symfony/security-core/blob/cf32ef36ed29872752b1537679201a3d51beaab2/Authorization/Voter/ExpressionVoter.php#L112) (for access_control expressions). I think it's a better solution to register a new global expression language function: `request_to_psr7()` or the like.

**Comment by stof** [comment]
The swiftmailer bridge is only about the profiler integration, so nothing to do here

**Comment by stof** [comment]
and symfony/security-core also depends on HttpFoundation on simple authenticators, which should actually have been provided in Http rather than Core (because this is the distinction between Core and Http)

**Comment by stof** [comment]
The translation component usage is only about the profiler integration, so nothing to do here (until the profiler is rewritten)

**Comment by WouterJ** [comment]
@stof the simple authenticators are moved to Security\Http in 2.8

**Comment by WouterJ** [comment]
I'm not so sure for the TwigBridge. A Bridge means that it's providing some classes that integrate Symfony in 3rd party libs (like Twig). So it's logical that they implement HttpFoundation and I'm not sure if it's logical to implement PSR-7 here. Seems like a TwigPsr7Extension in the twigphp organization can do a better job. For the record, HttpFoundation usage in the TwigBridge:

* `HttpFoundationExtension` - to implement the `absolute_url` and `relative_path` functions
* `AppVariable` - the global `app` var in Symfony full-stack templates
* The data collector

**Comment by nicolas-grekas** [comment]
Closing because this is not something with a well defined target (we don't know which/how components need psr-7 support). If someone want psr-7 support for a component, please open a PR :)
