### ISSUE TITLE
[FrameworkBundle] Move compiler passes in their component

### ISSUE THREAD

**Issue by chalasr** [symfony/symfony#21284]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Symfony version  | 3.3

Helps when using them independently with the DI component (also giving it visibility).
The most part are unlikely to be extended as is, they can be deprecated/moved in 3.3 (wired only if the component is installed) and removed from the framework in 4.0.

- [x] AddConsoleCommandPass => Console (#19443)
- [x] FormPass => Form (#21283)
- [x] SerializerPass => Serializer (#21293)
- [x] ConfigCachePass => Config (#21375)
- [x] RoutingResolverPass => Routing (#21835)
- [x] PropertyInfoPass => PropertyInfo (#21806)
- [x] ControllerArgumentValueResolverPass => HttpKernel (#21815)
- [x] AddConstraintsValidatorPass, AddValidatorInitializersPass => Validator (#22081)
- [x] ValidateWorkflowsPass => Workflow (#22313)
- [x] AddCacheWarmerPass, AddCacheClearerPass => HttpKernel (#22620)
- [x] TranslationDumperPass, TranslationExtractorPass, TranslatorPass => Translation (#22619)

**Comment by dunglas** [comment]
It has already been discussed several time and I think most people agree that it's a good idea. It's in the spirit of what we try to do with 3.3 too. 👍 for me.

**Comment by javiereguiluz** [comment]
👍  it makes a lot of sense to me and I can't see any drawback so far.

**Comment by ro0NL** [comment]
See also #20250 where the approach is to make special names configurable (imo. this is nice for the component part of it).

However the console passes were merged anyway (https://github.com/symfony/symfony/pull/19443#issuecomment-255525343), so im curious about the general approach here..

Not doing it, means the pass is pretty much useless for people wanting to do different naming. Which raises the question; is it worth it?

Besides, the console pass practically _only_ sets `console.command.ids` as a parameter; is it really component worthy?

**Comment by fabpot** [comment]
I think it makes sense. Let's do it.

**Comment by chalasr** [comment]
@fabpot See #21283 for the Form.

**Comment by chalasr** [comment]
@ro0NL Outside of the special name handling, having passes in the components make the DI component and the whole tagging feature discoverable/available when using the component standalone.

About the special name handling, the feature could be added in a next time (sure, not passed through the constructor), moving passes will at least give the idea of using the DI component for achieving such needs if the built-in passes do not fit. So yes, I do think it's worth it.

**Comment by ro0NL** [comment]
:+1: for as is moving to the components... just mentioning different approaches already :)

There was also discussion about some generic approach, i can imagine we can simplify some passes with a 

```php
new DI\TagCollectingPass('target.def', ['tagA', 'tagB'], function (Def $targetDef, Def $taggedDef, array $tagAttr) {
   $targetDef->addMethodCall('addTagAorB', $taggedDef);
});
```

Perhaps something to look into.

**Comment by Simperfit** [comment]
👍

**Comment by chalasr** [comment]
@ro0NL Applied your suggestion to make service id/tag names configurable through the constructor in #21283 and #21293

**Comment by chalasr** [comment]
@fabpot I'm going to propose the remaining passes and I wonder: would you prefer one huge PR or several ones?
