### ISSUE TITLE
[HttpClient] Next steps

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#30502]
Our shiny new HTTP client (see #30413) raised some comments. Some of them are about missing features. I'm opening this RFC to keep track of them. If anyone would like to work on any item, it'd be very welcome. I'm adding the "help wanted" label to hopefully make this call more visible.

- [x] #30494 add TraceableHttpClient and integrate with the profiler
- [x] #30661 Add a Record & Replay callback to the MockHttpClient
- [x] #31885 the `on_progress` callback could benefit from an additional `?string $chunk` argument - it might be helpful e.g. to catch response's contents in `TraceableHttpClient` or any other decorators that want to monitor the content
- [x] ~creating clients with custom behavior requires writing decorators. The component provides no base class to help to do so. It might be useful to provide an abstract one for this purpose. See https://github.com/symfony/symfony/pull/30413#issuecomment-469902643 and following comments.~ (not actionable, please proceed if you want)
- [x] #31883 the "buffer" option is required to allow accessing the content several times, but it should really be turned to false when downloading large files. We discussed with @joelwurtz about an "auto" mode, which could be the default one, and which would look at the content-type of the response to auto-enable buffering for some content types only. If anyone wants to take that task, please open a separate issue/PR to discuss more precisely how this could work.
- [x] #31884 `NativeHttpClient` currently relies on the native `http` stream wrappers. This means sending a request is blocking until the response headers come back. We discussed that with @joelwurtz: porting his [socket client](https://github.com/php-http/socket-client) to the component could remove this limitation. It would also allow sending requests through unix sockets, which only `CurlHttpClient` can do right now. A better alternative might be to create an `ArtaxHttpClient` based on https://github.com/amphp/artax.
- [x] #31641 at least for debugging purposes, it could be useful to give access to the full headers that were sent to the remote server. Two ideas: that could be done by the logger - it would then be implementation-dependent; or we could add a new `request_headers` entry to responses' `getInfo()`.
- [x] #30537 logger integration - to me, this should be done by injecting a logger into existing implementations (a logging middleware wouldn't allow accessing some internal things that might be useful to debugging)
- [x] #30419 FrameworkBundle integration: autowireable alias + semantic configuration for default options
- [x] #30604 add a mock client - a client that would return fake responses to help writing tests. Note that unlike [HTTPlug's Mock Client](http://docs.php-http.org/en/latest/clients/mock-client.html?highlight=mock#fake-responses-and-exceptions), collecting requests could be delegated to the `TraceableHttpClient` and the profiler service instead. To be discussed in a separate issue of course. Achieving parity with [CsaGuzzleBundle's mock middleware](https://github.com/csarrazi/CsaGuzzleBundle/blob/master/src/Resources/doc/available_middleware.md#the-mock-middleware) could be a nice goal.
- [x] handling of cookies is "do it yourself" right now. Defining a `cookie_jar` option could be useful. Or maybe an option is not the correct way. More ideas welcome in a separate issue/PR.
- [x] we could provide a decorator that would add HTTP and/or HSTS caching. Using `HttpCache` internally would be awesome :)
- [x] have exceptions carry responses
- [x] support for multipart/form-data
- [x] ~`CurlHttpClient` works on steroids with HTTP/2 thanks to multiplexing and server pushes, but this is untested right now. We could use the symfony CLI binary to build such a test suite. That would allow testing HTTPS features also.~
- [x] ~provide a way to inject custom curlopts (not sure we should personally - existing options already cover most of them)~
- [x] ~provide a way to inject custom JSON flags (not sure we should personally - ppl can always encode/decode on their own if they really want precise control on these)~
- [x] ~expose API with URI manipulation (not sure we should personally - future will tell)~

**Comment by fabpot** [comment]
I'm going to take the following items:

"support for multipart/form-data"
"we could provide a decorator that would add HTTP and/or HSTS caching. Using HttpCache internally would be awesome :)"
"handling of cookies is "do it yourself" right now. Defining a cookie_jar option could be useful. Or maybe an option is not the correct way. More ideas welcome in a separate issue/PR."

**Comment by antonch1989** [comment]
I could try with the logging integration

**Comment by antonch1989** [comment]
I'll also take `have exceptions carry responses` if there are no objections

**Comment by stof** [comment]
>     * `NativeHttpClient` currently relies on the native `http` stream wrappers. This means sending a request is blocking until the response headers come back. We discussed about that with @joelwurtz: porting his [socket client](https://github.com/php-http/socket-client) to the component could remove this limitation. It would also allow sending requests through unix sockets, which only `CurlHttpClient` can do right now.

should it be a separate client implementation instead ?

**Comment by antonch1989** [comment]
I'll work on giving access to the full headers that were sent to the remote server

**Comment by nicolas-grekas** [comment]
> I'll work on giving access to the full headers that were sent to the remote server

thanks - it should be done using `CURLINFO_HEADER_OUT` for curl - and mimicking the resulting behavior in `NativeHttpClient` as much as possible

(but please let's move your "logger" PR before:)

**Comment by antonch1989** [comment]
I investigated a bit with `CURLINFO_HEADER_OUT`. It is straightforward if there are `curl_init` -> `curl_setopt` -> `curl_exec` -> `curl_getinfo` calls, in this case the info will have `request_header` key if `CURLINFO_HEADER_OUT` option is set. 

In case with multi handlers it doesn't work. There is no `request_header` key in CurlResponse::getInfo
if I set an option here
![header_out](https://user-images.githubusercontent.com/8297194/54765795-3049b980-4c0b-11e9-9b16-d539621cba3d.png)

Probably doing this with the logger is not a bad idea in our terms

**Comment by sleepyboy** [comment]
$options['query'] should support array parameters. For instance, if I pass $options['query']['category'] = ['news', 'sport', 'culture'] to my GET request, I expect this to be transformed to `URL?category[]=news&category[]=sport&category[]=culture`. Maybe it makes more sense to use a standard PHP function `http_build_query` to build a final query.

**Comment by mxr576** [comment]
Any plans for a Guzzle 6 adapter that could provide some kind of backward-compatibility? Is somebody already working on that? HTTPlug has a [Guzzle 6 adapter](https://github.com/php-http/guzzle6-adapter), even it is not perfect, some async calls are not working with that, it is useful in many situations.

**Comment by nicolas-grekas** [comment]
@antonch1989 I implemented debug info in #31641, no need to care about `CURLINFO_HEADER_OUT` anymore as this provides more

@mxr576 There's no plans I know about regarding Guzzle<->HttpClient adapters. Someone interested would need to provide it (not necessarily in core btw.)

**Comment by nicolas-grekas** [comment]
Thank you all for your help, all remaining tasks have either PRs or issues, time to close this one!
