### ISSUE TITLE
[Messenger] Making it Shine

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony#30540]
Messenger is great. But, we've only carried it 90% of the way. It's missing key features and key things to *really* make it as usable as it deserves to be. Similar to #30502, I'd like to ask for help & ideas from the community to *really* make it shine.

(Note: in some of these cases, we just need more review & testing to help push PR's forward).

* [ ] Validate transport options with OptionsResolver
* [ ] Some sort of decent dashboard (or integration) to get stats about the health of your queues
* [ ] Some support, docs, something, for spinning up multiple workers, restarting them, etc
* [ ] Allow 3rd parties to define virtual transports and the user them maps to real transports
* [ ] Review [pending doc PRs](https://github.com/symfony/symfony-docs/pulls?q=is%3Aopen+is%3Apr+label%3AMessenger)
* [ ] Review [pending doc issues](https://github.com/symfony/symfony-docs/issues?q=is%3Aopen+is%3Aissue+label%3AMessenger)
* [x] #30970 Handling & Tracking Failed Messages Support
* [x] #31288 make BusNameStamp option for migration path
* [x] #30917 redis adapter
* [x] #30958 Allows to register handlers on a specific transport
* [x] #30957 Remove base64_encode from PhpSerializer
* [x] #30558 (and #29950 #28772) Transport Configuration & priority support (and retry attempts, etc)
* [X] #29040, #29097 null transport
* [x] #30020 Calling all handlers, even if one fails
* [x] #30008 multiple queues & routing key support for AMQP + routing key Envelope
* [x] #30757 get size of messages waiting in a transport
* [x] #30670 make sure bus service ids are consistent
* [x] #30707 Adding argument to MessageBus::dispatch() for envelopes
* [x] #30756 Fix serialization problem with empty messages
* [x] #30759 sync transport
* [x] #30676 dispatch send event not on retry
* [x] #30708 Move receive loop into Worker and allow supporting multiple transports
* [x] #30628 transport-by-transport serialization config
* [x] #29007 Doctrine transport (the Enqueue adapter is great, but we should support *some* basic adapters in core)
* [x] #30754 Command to stop/restart all workers
* [x] #29303 `messenger:consume` has no output
* [x] #30557 (~~#27215~~ ~~#27008~~) Retry mechanism
* [x]  #30557 (~~#29132~~)  Making `messenger:consume` not fail when a worker fails
* [x] #30557 Hook on worker failure so it can be handled/logged
* [x] #30764 log error when messages fail on Worker
* [x] #30650 Allow stamping messages dispatched by 3rd parties via events
* [x] #30631 sent received messages to the correct bus automatically
* [x] ~~#30634 Possibly allow each handler of a message to be sent to a different transport (e.g. 1 handler async, 1 sync) and when received, only the 1 handler is executed.~~
* [x] #29476 Command to setup transports
* [X] #28849 Doctrine transaction support
* [x] #30671 amqp prefetch

What else?

**Comment by Nyholm** [comment]
This is also needed imho https://github.com/symfony/symfony/pull/28849

**Comment by Toflar** [comment]
> What else?

Not sure if this was discussed before (searched GitHub but did not find what I was looking for) but I'm missing priority support. I think this is a crucial missing feature that Enqueue already provides (but not for all adapters). Things like user interaction (such as sending e-mails) should always have higher priority than other jobs so I really like that I can give a message a certain priority. I think with the current stamp concept it might be possible (`PriorityStamp`) and there are transports that support it natively like e.g. RabbitMQ with `x-max-priority`. For Redis we could use sorted sets, for DBAL it's just an indexed `priority` column and an `ORDER BY` etc.

**Comment by Nyholm** [comment]
That is a great point. However, I think it is outside of the scope of the Messenger. We should however document how to achieve that. 

Quick howto: You add some AMQP routing metadata on your messages and make sure your transport supports adding the routing key to the AMQP message. Then you can configure your exchange to move some messages to a "high priority queue". Then you need to use a consumer that consumes from a list of queues. 

It sounds like a lot, but it is just "implementation details".

**Comment by er1z** [comment]
So far, my list:

- [ ] event listener on failed job (with particular job as an argument); as well as more events just like the Request has. But on failed is more essential,
- [ ] use `__invoke` result as an output, for example on every succeeded job I want its ID to be written on stdout

**Comment by weaverryan** [comment]
> event listener on failed job (with particular job as an argument); as well as more events just like the Request has. But on failed is more essential,

I've talked a little bit about this here: https://github.com/symfony/symfony/pull/29132#issuecomment-472099292

I tend to agree: the worker should not fail, and we should dispatch some events. Could you open a PR for this? 

> use __invoke result as an output, for example on every succeeded job I want its ID to be written on stdout

I don't understand this one - you *can* already fetch the return value from `__invoke()` - if that's what you need - https://symfony.com/doc/current/messenger/handler_results.html

**Comment by weaverryan** [comment]
> I'm missing priority support. 

💯 I'd like to support (in all transports) a few common options, like priority, delivery delay, retry attempts, etc. Probably we should create a transport that can support all of these. We should propose this as soon as possible in a PR, because we need to get a few other transports merged AND make them support these before feature freeze at the end of March if we want to get things done for 4.3 (which I do).

I've opened #30558 to discuss and have added to the list.

**Comment by er1z** [comment]
> I don't understand this one - you can already fetch the return value from __invoke() - if that's what you need - https://symfony.com/doc/current/messenger/handler_results.html

I mean the result result of `__invoke` = data written to stdout by worker command or sth.

**Comment by nicolas-grekas** [comment]
Please discuss this in another issue.

**Comment by f2r** [comment]
I haven't see this issue, but is me PR could help ? https://github.com/symfony/symfony/pull/30454

**Comment by weaverryan** [comment]
@f2r Just added your PR to my list above. Indeed, I like where you're going with that PR :)

**Comment by antonch1989** [comment]
@weaverryan is there something relatively easy I could start with?

**Comment by Nyholm** [comment]
@antonch1989 how about null transport? Or many redis transport?

**Comment by weaverryan** [comment]
Both of those have PR's already. However, reviewing and actually *testing* those would be an awesome way to start helping :). There aren't a lot of "easy pick" issues right now with this stuff.

**Comment by enumag** [comment]
Maybe handlers should receive the envelope or array of stamps as second argument? Some of the metadata from stamps might be usefull for a handler in my opinion. I can send a PR.

**Comment by Guikingone** [comment]
Small question, what about adding a `filesystem` transport in the component? (without using an external library).

**Comment by fabpot** [comment]
@Guikingone I would not add such a transport, which is very fragile. We already have Doctrine and in memory, I think that's more than enough.

**Comment by Toflar** [comment]
PDO/Doctrine and SQLite basically is filesystem. Why re-inventing the wheel? :)

**Comment by Guikingone** [comment]
Enqueue has both 😄 

In fact, the idea was to have a dedicated `filesystem` transport in order to get rid of Doctrine/RabbitMQ/Redis usage in test env but as fabpot says, the `in-memory` transport is already in place 😃

**Comment by vasilvestre** [comment]
What do you think about allowing empty "type" headers to allow simpler message? 
Use case: Having a queue with one class only that's used to receive a small message and dispatch notification

**Comment by weaverryan** [comment]
That will be possible in 4.3 like this:

1) Create a custom serializer that reads in your JSON and converts it into a message. This class could be dead-simple, as you could use the `serializer` service to deserialize right into whatever object you want.

2) Set that custom serializer as the serializer for some transport - because in 4.3 it's possible to set serializers on a transport-by-transport basis.

The `messenger:consume` command will also be able to consume from multiple transports at once, so if you have 5 transports with this style, you can consume them all at one time.

Btw, about point (1), you *should* also implement the `encode(Envelope $envelope)` method in your serializer and make it actually properly encode the Envelope/Stamps in a way that your `decode()` method understands if you want the new, automatic retry mechanism to work. Or, if this message originated from an external system (I'm guessing this is the case for having raw JSON without any type headers), you could configure the message class to "route" to some normal transport that uses the normal serialization. Then, you would consume it through your custom transport, but it would be retried through another transport, which uses normal serialization.

**Comment by weaverryan** [comment]
Closing this issue as incredible progress has been made on Messenger! Thanks for everyone who helped. Let's continue tracking individual items on new, individual issues.

Cheers!
