### ISSUE TITLE
[RFC] Symfony Security rework tracking issue

### ISSUE THREAD

**Issue by curry684** [symfony/symfony#30914]
After discussions at EU FOSSA Hackathon we have some ideas on how to rework the Security component. I'm writing this "tracker issue" to gather up the info and choices made thus far.

The biggest functional issues have been discussed frequently over the years (https://github.com/symfony/symfony/issues/10316 and others) that the authentication makes some shortcut assumptions no longer valid in 2019:
- The object of security considerations is not always a user, it may be a device, a computer, an API key, or any number of other abstract things. In the security world the concept of "something that can participate in security questions" is called a Principal.
- There should be a functional separation between the Principal performing an action and the Context he is in while doing so. Authorization decisions should be based on the presented Context. This solves many practical issues like impersonation and "act as company".
- Principals may be authenticated by various means, and be oblivious themselves on the subject. Principals should therefore not expose functionality to get passwords or roles as they may not have any. Tokens handle authentication.

The Symfony Security component was originally based on the Java Spring Security framework, but has deviated over the years. Today Spring Security has both fixed some structural issues that Symfony has (the notion of principals versus users and no central assumption that passwords and roles exist) and has some features that are currently lacking or hacky at best (structural support for OpenID/OAuth, support for 2FA). Conclusion for now is that most of the current Security component, especially authorization, is mostly fine and does not need a lot of work, and it wouldn't be all that hard to fix the authentication parts, and more strongly decouple authentication and authorization, by taking some current inspiration from Spring again.

Once these changes are propagated a lot of other features related to authentication should be easier to implement. Wishlists have been assembled:

Authentication
=
- [x] User impersonation (including multiple impersonation without having to log out) *not affected by Security changes*
- [x] <s>Social login (login in the app using Google, Facebook, GitHub, Twitter, etc.) and generic OAuth support</s> (https://github.com/symfony/symfony/pull/31952#issuecomment-698424823)
- [x] Login throttling (limit the number of failed login attempts over a period of time)
- [ ] Simultaneous session limiting (e.g. each user can login only from one device at the same time)
- [x] <s>Two-factor (or multi-factor) authentication</s> (https://github.com/symfony/symfony/issues/28868#issuecomment-774069638)
- [ ] “Sudo mode” (trigger a new authentication before sensitive operations, like GitHub) (#33955)
- [ ] Native JWT implementation if some package is available (firebase/php-jwt ?)
- [ ] CSRF on router level 
- [x] User checkers (allow to make checks after user has logged in to block the log in if needed)
- [x] LDAP (authenticate against a LDAP server) *not affected by Security changes*
- [ ] Support for third-party authentication services (e.g. Auth0: https://auth0.com/)
- [ ] Support for SAML 2.0 (authentication and federation mechanism)
- [x] Support pre-authentication mechanisms (e.g. X.509 certificates, Request-Header authentication, etc.)
- [x] Have a centralized token invalidation mechanism (https://github.com/symfony/symfony/issues/30914#issuecomment-480795520) (https://github.com/symfony/symfony/pull/40145)
- [x] Easy to add new authentication mechanisms (as Guard currently offers)
- [x] Easy customization of provided authentication mechanisms (especially form_login, which is the most complex and most used one): through events/hooks? Or implement those as Guards, we can easily decorate/override?
- [x] More events: at least having an event before a login is attempted, which could be used to implement custom rate-limiting mechanism
- [ ] Constant timing user login for non-existent user (to protect leaking existence of a user) - see https://github.com/paragonie/airship/blob/8f04f071c414c3893cf66311839d20a343af1237/src/Engine/Security/Authentication.php#L161-L168 for technical details

Authorization
=

- [x] "Access control" to set permissions over web site sections using regexps *not affected by Security changes*
- [x] Native @Security annotation to set the permissions of controller classes and/or actions *not affected by Security changes*
- [ ] Grant or deny permissions based on trust levels, such as whether 2FA is enabled or "sudo mode" is required
- [ ] Having an opinionated way to set up object-level control mechanism (CRUD). Voters tend to be a little bit too general in my opinion, making necessary to set up per project conventions (ie, you have to check for “EDIT” attribute…), which can’t be enforced programmatically now.

Users
=
Dropping the notion of users at the lowest level must not mean DX suffers and developers need to write a lot of boilerplate again. In fact directly implementing `PrincipalInterface` should likely be considered an advanced subject, and we should provide a layer with abstract and stock implementation of common user-based scenarios:

- [x] Allow to represent application users with a User class (bonus: help you create it with make:user). *not affected by Security changes*
- [x] Allow to get a User object very easily from a Twig template. *not affected by Security changes*
- [ ] <s>Allow to easily differentiate anonymous users and logged in users.</s> (https://github.com/symfony/symfony/pull/36574#issue-408764998)
- [x] “Remember Me” feature (access to the app without having to log in again; and allow to differentiate those users from both anonymous users and users who logged in for real) (#40145)
- [x] Roles (to have different kinds of users: normal users, admins, etc.) *not affected by Security changes*
- [x] Allow to hash user passwords (Bcrypt, Argon2i, etc. but not old algorithms with custom salts) (
- [x] Password rehashing (to upgrade from Bcrypt to Argon2i transparently) (#39802)
- [x] "I forgot my password" (implemented as `make::reset-password`)
- [x] Email validation on registration (tracked in https://github.com/symfony/maker-bundle/issues/542)
- [x] Allow to log in users programmatically in an easy way (e.g. `$security->login(‘username’)`)
- [x] Make it trivial to test protected resources (logging in a user in tests should be very easy)
- [ ] Password validators (check if password is too simple, if it has been compromised before, etc.)
- [x] Have minimal requirements/assumptions about User class from Security component, so decoupling is easier (which is a pretty popular topic, actually). Only requiring username/password, likely? (#40267)

Non-wishlist
=
- As we are committed to using voters for authorization, and do not want to have/support 2 mechanisms serving similar or mostly identical purposes we will not implement ACLs again

/cc @wouterj @derrabus @linaori @sstok

**Comment by quentinus95** [comment]
Following your comment on #28868, I wanted to add what I wrote there about authentication.

The current implementation considers authentication as a binary state (authenticated / not authenticated), and we use additional roles and rules (IS_AUTHENTICATED_FULLY) to determine the amount of trust we give to the authenticated principal.

The main issue is that we use authorization to describe something purely related to authentication. Something interesting could be to change this idea of binary status and replace it with a level of trust (e.g. an authentication through a form_login gives you 100 points). Having a 2FA form / using the remember me feature / having multiple factors could have an impact on this level of trust (e.g. using login_form + 2fa gives you a total of 150 points, using remember me gives you a total of 80 points, ...).

We could use this mecanism to ease authentication controls by defining, for instance, a minimal level of trust either using firewalls or path based security rules. This would give a lot of flexibility to craft advanced authentication mecanisms.

**Comment by curry684** [comment]
@quentinus95 interesting thoughts. You should however remember that the process of authentication itself is handled by Tokens, so the process of how an authentication chain ends up at a certain level of trust should be handled there. This is even already being improved by the proposal at https://github.com/symfony/symfony/issues/30765.

In a nutshell right now we're pretty limited with the RememberMeToken granting `IS_AUTHENTICATED_REMEMBERED`, and just about every other one ends up with `IS_AUTHENTICATED_FULLY`. We'll need more granular control there to indeed implement some of the scenarios you describe and are also in some form in the to-do list of this RFC, specifically
- Require 2FA to be enabled for the user for certain highly dangerous actions
- Implement "sudo mode", requiring reauthentication to temporarily get into an "elevated" authentication

**Comment by curry684** [comment]
Updated RFC with some minor things:
- Added trust levels to authorization section
- Renamed Identity to Context to comply with Spring terminology and to reduce confusion with .NET which implement Identity a bit differently)
- Clarified object level permission description to explicitly mention CRUD, there should be some easily usable extension to Voters to implement CRUD functionality at object/entity levels

**Comment by vudaltsov** [comment]
@curry684 , this is a great list, thank you!

I have some thoughts:
- Manual authentication. Useful when authenticating user right after he has signed up.  This is a common question which is usually solved by copying https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Security/LoginManager.php and a hackish compiler pass for remember me into the project.
- A centralized token invalidation mechanism. It seems that tokens should not validate themselves — it's not flexible and extensible. Consider a scenario, when some security issue happens at the website, and you need to invalidate all logins at your website after a fix. Currently there's no easy way to deactivate `RememberMeTokens`. Once in Slack I proposed to add a `TokenValidatorInterface`.

  ```php
  interface TokenValidatorInterface
  {
      public function supports(TokenInterface $token): bool;

      public function isValid(TokenInterface $token/*, $someOtherArgs */): bool;
  }
  ```

  By the way, the code from `AbstractToken::hasUserChanged()` could be implemented under such an interface easily.

**Comment by teohhanhui** [comment]
Relevant comment on password rehashing: https://github.com/symfony/symfony/pull/31019#issuecomment-482171738

**Comment by curry684** [comment]
@vudaltsov first one is already on the list as manual authentication, second one added, thanks!

@teohhanhui given that in that issue "the framework" has made a choice on the subject I'm not seeing an RFC item there. It's of course a valid discussion but not something to have here right now I think.

**Comment by teohhanhui** [comment]
@curry684 Not the PR, but my comment. Well, I should just put it here:

https://docs.spring.io/spring-security/site/docs/5.1.5.RELEASE/reference/html5/#pe-dpe
https://docs.spring.io/spring-security/site/docs/5.1.5.RELEASE/api/org/springframework/security/crypto/password/DelegatingPasswordEncoder.html
https://docs.spring.io/spring-security/site/docs/5.1.5.RELEASE/api/org/springframework/security/crypto/factory/PasswordEncoderFactories.html#createDelegatingPasswordEncoder--

**Comment by curry684** [comment]
Hmm interesting, thanks  👍

**Comment by rpkamp** [comment]
For logging throttling you could also consider device cookies: https://www.owasp.org/index.php/Slow_Down_Online_Guessing_Attacks_with_Device_Cookies

**Comment by Guikingone** [comment]
Hi 👋 

I was thinking about the OAuth provider, what about using the `HttpClient` and provide a default system similar to what is available in PHPLeague: https://github.com/thephpleague/oauth2-client ? 🤔 

Any idea?

**Comment by stephanvierkant** [comment]
Is this the right issue to note that `\Symfony\Component\Security\Core\User\UserInterface::getSalt()` makes no sense with modern hashing functions?

**Comment by chalasr** [comment]
I'm going to work on the JWT part.

**Comment by ro0NL** [comment]
> Is this the right issue to note that `\Symfony\Component\Security\Core\User\UserInterface::getSalt()` makes no sense with modern hashing functions?

for this id like to propose a new contract, as we're heading for `encodePassword($pass, null)` and have this useless arg

**Comment by linaori** [comment]
Salt isn't recommended to be stored separately if I understood it correctly. As long as we change it to `hashPassword`, I'm all good with the change 😉

**Comment by ro0NL** [comment]
> Password rehashing

@curry684 this one is solved in #31594 / #31843 i believe

**Comment by teohhanhui** [comment]
I think what's still very disturbing to me is that the app developer will completely lose control over which password hashing algorithm to use.

What's worse, if you have a scenario where you upgrade your PHP version / sodium extension and a new algorithm becomes supported, then if you rollback the app, the password would then fail to verify. There is no way to prevent this from happening if the app developer is forced to use `auto`.

**Comment by ro0NL** [comment]
i quite like the idea we get the best hashing algo, and it just works :)

> then if you rollback the app

isnt that an unlikely scenario, and kinda asking for problems (perhaps not just invalid password hashes)

**Comment by derrabus** [comment]
When performing php minor version updates for large production environments, it is a valid approach to not update all webservers at once. In that scenario, where we have php 7.n and 7.(n+1) installations operating on the same database for a couple of days or weeks, there would be a need to pin the password hashing to the capabilities of the older php release.

**Comment by teohhanhui** [comment]
> i quite like the idea we get the best hashing algo, and it just works :)

I like it too. It's a good default. But I don't like when choice is taken away from developers.

**Comment by chalasr** [comment]
Same edge case applies with `sodium_crypto_pwhash_str()` (used by the deprecated Argon2iPasswordEncoder) and `password_hash(..., PASSWORD_DEFAULT)`. 
Please open a dedicated issue if you want to deepen this (or anything else that is already implemented) so that this one keeps serving to discuss new ideas.

**Comment by curry684** [comment]
I should be noting publicly here (shared it on Slack before) that my "corporate duties" have been rather overwhelming the past few months, reducing my actual programming time tenfold. So I regrettably have no time to actually do anything myself for the foreseeable future. I'll be following all topics where I'm highlighted though and am glad to see the writeup I did at EUFOSSA turns out to be universally accepted and useful   😄

**Comment by wouterj** [comment]
Sudo mode: https://github.com/symfony/symfony/issues/33955

**Comment by jkufner** [comment]
## Immutable Value Objects

The use of Doctrine for persistence tends to influence API designs in subtle ways that complicate the use of persistence layers based on different concepts (e.g.,  [CQS](https://www.dotnetcurry.com/patterns-practices/1461/command-query-separation-cqs)). Please make sure that you avoid as much assumptions on persistence layers as possible, even for reading.

It would be nice to make a few explicit statements, for example that Tokens are immutable, or that UserInterface is an immutable value object, not only a DTO (the difference is in equivalence definition: value objects equal when they contain the same value, but DTO does not define such a thing).

When I was implementing my custom security component, I found the tokens are a good Idea, but their workflow is a bit confusing and complicated. This may be only a matter of documentation, but some clarification would help.

Another thing is the `UserInterface` interface. I think that the whole concept of a User entity in the security component is flawed (and the result of the Doctrine influence I mentioned in the beginning). There should not be a User in the first place. The `UserInterface::getPassword()` method assumes the User entity knows its (hashed) password; that may not be the case at all (e.g., SSO or LDAP). Instead, there should be a `UserIdentity` entity — a *value object* that identifies the user (or a principal in general). Then there should be a service that answers the questions of the authentication component, like "Is this password for this user identity valid?" or "Does the user of this identity have this role?", or even better "Does the user of this identity fulfill these constraints?". Such a separation will make the whole security component more robust and versatile. Moreover, it will concentrate the decissions in one place so that the code will be easier to understand and more secure (no `User::eraseCredentials()` method needed because the passwords never leave the question answering service and the tokens).

**Comment by vudaltsov** [comment]
@jkufner , fully agree. In fact Doctrine does not make you break encapsulation. I do DDD with absolutely no getters and setters and still map my aggregates successfully with Doctrine, since it works with properties directly. So what you say can be achieved with Doctrine as a possible persistence manager as well.

**Comment by ro0NL** [comment]
CSRF: https://github.com/symfony/symfony/issues/34004

**Comment by hktr92** [comment]
I have an internal web app at work that requires impersonation chaining. the current impl supports only one impersonation and there are issues when you impersonate yourself (you shouldn't be allowed to do so). so it might be useful to be in the wild, but defaulting to allow a single impersonation in the chain.

I'll try to experim this feature internally (and bug fixing) and if it were to be implemented in the base code, i'll be willing to implement it in the component.

**Comment by hkdobrev** [comment]
Could we have new Symfony contracts for the token interface and the user interface if applicable? What do you think?

**Comment by linaori** [comment]
@hkdobrev see #35237, unless there's a very good reason, I don't think it will happen

**Comment by wouterj** [comment]
With the merge of the new experimental security (ref #33558), the following boxes can be thicked 😃 

**Authentication**

- User checkers (allow to make checks after user has logged in to block the log in if needed)
- LDAP (authenticate against a LDAP server)
- Support pre-authentication mechanisms (e.g. X.509 certificates, Request-Header authentication, etc.)
- Easy to add new authentication mechanisms (as Guard currently offers)
- Easy customization of provided authentication mechanisms
- More events: at least having an event before a login is attempted, which could be used to implement custom rate-limiting mechanism

**Users**

- Allow to log in users programmatically in an easy way (e.g. `$security->login(‘username’)`)
- Make it trivial to test protected resources (logging in a user in tests should be very easy) (implemented by #35997)

**Comment by curry684** [comment]
Nice work! I don't think you need me to physically tick them right?

**Comment by wouterj** [comment]
@curry684  I don't have special permissions for the symfony/symfony repository. So either you or a core team member can thick them.

**Comment by jrushlow** [comment]
From the original post:
>  "I forgot my password" (provide a default implementation for that or simplify a lot its implementation) (Note: currently under review in the MakerBundle)

This feature has been implemented in the maker bundle `make:reset-password` using `symfonycasts/reset-password-bundle`

https://github.com/symfonycasts/reset-password-bundle

**Comment by jrushlow** [comment]
Another user related function would be email verification. This is also a WIP and should be ready soon. 

https://github.com/symfony/maker-bundle/issues/542

**Comment by curry684** [comment]
Cheers, updated OP!

**Comment by jrushlow** [comment]
> Another user related function would be email verification. This is also a WIP and should be ready soon.
> 
> [symfony/maker-bundle#542](https://github.com/symfony/maker-bundle/issues/542)

@curry684 We just merged this in a few moments ago - another check mark on the list

**Comment by curry684** [comment]
@jrushlow checked off   😄

**Comment by mynameisbogdan** [comment]
Since #40275 was deleted, `hide_user_not_found` will be supported?

/cc @wouterj

**Comment by wouterj** [comment]
@mynameisbogdan yes, please see https://symfony.com/security on how report security issues (I could find no way to contact you outside GitHub, so sorry for not being able to explain the deletion)

**Comment by wouterj** [comment]
So after a long ride, I think it's time to close this issue. Starting with this issue, the security component has received lots of attention the past 2 years. I'm happy to see that almost all items on this list are ticked off. The remaining ones are either on the list for 5.4 in specialized issues or already fixed by a community bundle (which we may or may not merge in Symfony one day).

Thanks a lot for everyone that has in some way been part of this long journey!

**Comment by stof** [comment]
Regarding password validators, I think we can consider it covered too:

- compromised passwords are covered in the core
- min length is covered in the core
- password complexity requirements are explicitly discouraged by the latest NIST password guidelines, so I'm fine with not having them in the core. For projects that still want to use them, there is https://packagist.org/packages/rollerworks/password-strength-bundle

**Comment by curry684** [comment]
It's been a happy ride indeed  👍 

See you next FOSSA event   😉 

> password complexity requirements are explicitly discouraged by the latest NIST password guidelines

@stof is the discouragement explicit and complete now? I'm fully aware requiring 'complex passwords' has been discouraged for good reasons for several years in most policies, *however* to my knowledge it has always been recommended to require _some_ basic level of entropy by disallowing dictionary words, excessively short passwords and common 'canned' passwords like `qwerty`, `nimda` or `1234`.

**Comment by wouterj** [comment]
@curry684 see https://pages.nist.gov/800-63-3/sp800-63b.html#memsecretver

> When processing requests to establish and change memorized secrets, verifiers SHALL compare the prospective secrets against a list that contains values known to be commonly-used, expected, or compromised. [...]
> Verifiers SHOULD offer guidance to the subscriber, such as a password-strength meter [Meters], to assist the user in choosing a strong memorized secret. [...]
> Verifiers SHOULD NOT impose other composition rules (e.g., requiring mixtures of different character types or prohibiting consecutively repeated characters) for memorized secrets. [...]

**Comment by curry684** [comment]
From the same link I was actually right:

> Verifiers SHALL require subscriber-chosen memorized secrets to be at least 8 characters in length.
> [...]
> When processing requests to establish and change memorized secrets, verifiers SHALL compare the prospective secrets against a list that contains values known to be commonly-used, expected, or compromised. For example, the list MAY include, but is not limited to:
> 
>     Passwords obtained from previous breach corpuses.
>     Dictionary words.
>     Repetitive or sequential characters (e.g. ‘aaaaaa’, ‘1234abcd’).
>     Context-specific words, such as the name of the service, the username, and derivatives thereof.
> 
> If the chosen secret is found in the list, the CSP or verifier SHALL advise the subscriber that they need to select a different secret, SHALL provide the reason for rejection, and SHALL require the subscriber to choose a different value.

Given that we cover minimum length and breach lists I agree it's enough and the rest is optionally pluggable. The confusion was in what 'complexity' entails, I consider disallowing dictionary words a complexity thing.

**Comment by pbowyer** [comment]
Thank you to everyone who's contributed, it's great to have these improvements in Symfony!
