### ISSUE TITLE
[5.0] Add parameter type-hints

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony#32179]
The current master branch (which will become Symfony 5) raised the minimum requirement of php to 7.2. That php version introduced a feature called [Parameter Type Widening](https://wiki.php.net/rfc/parameter-no-type-variance) that allows a class to drop parameter type constraints when overriding/implementing a method from a parent class/interface.

This opens up an interesting upgrade path for us: We can add new type-hints to interfaces without breaking implementations that were written against the non-typed version on that interface.

Things to watch out for:
* Start with interfaces and classes without parent.
* Don't add type-hints to contracts interfaces: we need php 7.1 compatibility here!
* You can only add type-hints, not change or remove existing ones.
* Don't add return types. They require a different strategy.
* Consult the docblock to find out if you can add a type-hint. But keep in mind that the docblock might lie to you.
* Adding a type-hint might break code that calls the method: Have a look at the implementations of the interface and their tests to find out what kind of values can be passed to the method right now.
* Check if `null` is a valid value. That case is often forgotten in type-hints.
* Adding a `callable` type-hint triggers autoloading if the passed value contains a class reference as string. This is a side-effect that should be considered.
* The method might contain now-obsolete type-checks. You may remove them.
* The added type-hints might obsolete `@param` annotations. Remove them if they only contain information that is already reflected by the type-hint and the parameter name.
* If you find an implementation or child class that is part of another component, don't upgrade the signature just yet if that components should remain compatible with the 4.4 version of the component you're currently working on.

In order to keep the changes reviewable, we should iterate over the components and open one PR per package.

### Components
- [x] Asset – @jschaedl – #32202
- [x] BrowserKit – @Simperfit – #32280
- [x] Cache – @Simperfit @Tobion – #32282  #32298
- [x] Config – @jschaedl @Tobion – #32201 #32286
- [x] Console – @Simperfit – #32318
- [x] CssSelector – @Simperfit – #32328
- [x] Debug – @Matts – #32217 – has been removed in 5.0
- [x] DependencyInjection – @derrabus – #32238, #32266, #32283
- [x] DomCrawler – @Simperfit – #32329 
- [x] Dotenv – nothing to do here.
- [x] ErrorRender – with return types on branch 4.4 as the component is new
- [x] ErrorHandler – with return types on branch 4.4 as the component is new
- [x] EventDispatcher – @derrabus – #31984
- [x] ExpressionLanguage – @Simperfit, @derrabus – #32346, #33196
- [x] Filesystem – @smoench – #32247
- [x] Finder – @smoench – #32243
- [x] Form – @vudaltsov – #32237
- [x] HttpClient – has been added in Symfony 4.3 and is probably fine.
- [x] HttpFoundation – @julien57, @azjezz – #32271, #33088
- [x] HttpKernel – @tigitz, @derrabus – #32276, #33195
- [x] Inflector – nothing to do here.
- [x] Intl – @tigitz – #32525 
- [x] Ldap – @Simperfit – #32253 
- [x] Lock – @Simperfit – #33004 
- [x] Mailer – has been added in Symfony 4.3 and is probably fine.
- [x] Messenger – has been added in Symfony 4.1 and is probably fine.
- [x] Mime – has been added in Symfony 4.3 and is probably fine.
- [x] OptionsResolver – @jschaedl – #32235 
- [x] Process – @tigitz – #32273
- [x] PropertyAccess – @jschaedl – #32234
- [x] PropertyInfo – @jschaedl – #32233 
- [x] Routing – @derrabus – #32176, #32181, #33191
- [x] Security/Core – @derrabus – #32351, #32352, #32353
- [x] Security/Csrf – @julien57, @Tobion – #32208, #32285
- [x] Security/Http – @andreia – #32314 
- [x] Security/Guard – @thomasbisignani – #32254
- [x] Serializer – @Simperfit, @derrabus – #32229, #33185 
- [x] Stopwatch – @jschaedl @Tobion – #32242
- [x] Templating – @derrabus – #32313
- [x] Translation – @Matts – #32218
- [x] Validator – @xabbuh, @derrabus – #32264, #33190
- [x] VarDumper – @derrabus – #33153
- [x] VarExporter – has been added in Symfony 4.2 and is probably fine.
- [x] WebLink – nothing to do here.
- [x] Workflow – @lyrixx – #32223
- [x] Yaml – @xabbuh – #23262, #32761

### Bundles
- [x] DebugBundle – @Matts – nothing to do here.
- [x] FrameworkBundle – @derrabus – #32480
- [x] SecurityBundle - @xabbuh - #32778
- [x] TwigBundle - @xabbuh - #32775
- [x] WebProfilerBundle – @Matts – #32216
- [x] WebServerBundle – has been removed in 5.0

### Bridges
- [x] Doctrine - @xabbuh - #32769
- [x] Monolog – nothing to do here
- [x] PhpUnit – nothing to do: needs to stay compatible with PHP 5.
- [x] ProxyManager – @derrabus – #32283
- [x] Twig - @xabbuh - #32774

**Comment by nicolas-grekas** [comment]
If we finish https://github.com/symfony/symfony/pull/30323, we might have a way to also add return types. I think @fancyweb would appreciate some help there.

**Comment by mdeboer** [comment]
@nicolas-grekas 
> If we finish #30323, we might have a way to also add return types. I think @fancyweb would appreciate some help there.

I'd be happy to help! As some PRs are already merged, does this mean work on this can be started?

**Comment by Matts** [comment]
No work required for DebugBundle

**Comment by Matts** [comment]
started on translator

**Comment by vudaltsov** [comment]
@derrabus , I am ready to help with Form component

**Comment by derrabus** [comment]
A small reminder: This ticket is about __parameter__ type-hints. Please do not add return types (yet).

**Comment by Tobion** [comment]
The title is wrong and people copy-paste this: It's not only about scalar types. We also want to add object etc paramter types.

**Comment by lyrixx** [comment]
Fixed

**Comment by Simperfit** [comment]
doing lock when #32198 is merge :).

**Comment by derrabus** [comment]
Updated the list, looking into DI now.

**Comment by nicolas-grekas** [comment]
Note that VarExporter is missing types on purpose: all internal classes are perf critical and types have a slight impact we want to avoid there. Don't accept a PR that changes the component on this topic please.

**Comment by tigitz** [comment]
Just a quick note about a tool that I used for https://github.com/symfony/symfony/pull/32273

You can automatically parse docblock params type hint and add them as real type hint by running https://github.com/rectorphp/rector with the following config file:

```yaml
# rector.yaml
services:
  Rector\TypeDeclaration\Rector\FunctionLike\ParamTypeDeclarationRector:
```

Docker one liner to run in the folder you're interested in:
```sh
docker run -v $(pwd):/project rector/rector:latest process /project --config /project/rector.yaml --autoload-file /project/vendor/autoload.php
```

Obviously, it only assists you on this specific task, human checks remains to be done.

**Comment by derrabus** [comment]
I'm looking into Security/Core now.

**Comment by ThomasCouet** [comment]
As WebServerBundle is already deprecated, and will be removed In 5.0, should it stay in this TODOList? 
Regards,

**Comment by derrabus** [comment]
@ThomasCouet You're right. I've updated the list.

**Comment by 8889abcd** [comment]
shit

**Comment by tigitz** [comment]
@derrabus Intl component is ready to be reviewed here: https://github.com/symfony/symfony/pull/32525

**Comment by nicolas-grekas** [comment]
I just ticked the last checkbox! :tada: 
Does this mean we can close here?
Can someone have a last look maybe?

**Comment by derrabus** [comment]
> I just ticked the last checkbox! 🎉

Hooray! A great thank you to everyone involved!

> Does this mean we can close here?
> Can someone have a last look maybe?

I'll have a look later today. But we should be good, I think. :-)

**Comment by derrabus** [comment]
Looking into VarDumper right now. We actually can add types here.

**Comment by derrabus** [comment]
All right, that should be it. 😓

**Comment by derrabus** [comment]
All right, I think we can close the issue now. Thanks a lot again to everyone who contributed to making the Symfony codebase a type-safer place! 😃
