### ISSUE TITLE
PHP 7.4 + PHPUnit 8.2 support

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony#32844]
~In #32842, I implemented a new `ForwardCompatTestTrait` in the phpunit-bridge to allow tests to run on the new php74-snapshot job, see #32289  This trait adds the `void` return type that phpunit 8 requires, while preserving compatibility with branch 3.4, which supports PHP 5.5. As a reminder, we target to make 3.4 run on PHP 7.4.~

As of #32882, the phpunit-bridge is able to run phpunit 4.8 to 8 and PHP 5.5 to 7.4. It does so by polyfilling some missing methods and by patching the return type of setUp*/tearDown* methods when needed.

Now, there are failures we need to overcome on PHP 7.4 + phpunit 8, as reported here:
https://travis-ci.org/symfony/symfony/jobs/567908746

~We need to implement polyfill methods in `ForwardCompatTestTrait` to allow fixing the deprecation warnings that phpunit 8 displays.~

With #32887 in place, the process would be:
1. open a PR against branch 4.4 to make the phpunit-bridge polyfill a missing feature when needed
2. open a PR against branch 3.4 with the fix applied, and with the `SYMFONY_PHPUNIT_BRIDGE_PR` set to the number of the previous PR in `.travis.yaml`
3. we'll merge 1. once things are validated, and you'll have to revert the change on `.travis.yaml` before we merge 2.

Here is the list of things that phpunit 8 reports and should be fixed:
- [x] #32969 The optional $checkForObjectIdentity parameter of assert(Not)Contains() is deprecated and will be removed in PHPUnit 9. Refactor your test to use assert(Not)ContainsEquals() instead.
- [x] #32968 The optional $delta parameter of assertEquals() is deprecated and will be removed in PHPUnit 9. Refactor your test to use assertEqualsWithDelta() instead.
- [x] #32971 Using assert(Not)Contains() with string haystacks is deprecated and will not be supported in PHPUnit 9. Refactor your test to use assertString(Not)ContainsString() or assertString(Not)ContainsStringIgnoringCase() instead.
- [x] #32923 readAttribute()/getObjectAttribute()/assertAttributeEquals()/assertAttributeSame() is deprecated and will be removed in PHPUnit 9.
- [x] #32909 assertArraySubset() is deprecated and will be removed in PHPUnit 9.
- [x] #32878 #32907 polyfill assertString(Not)ContainsString(IgnoringCase), assertEqualsWithDelta and assert(Not)ContainsEquals
- [x] #32875 The @expectedException, @expectedExceptionCode, @expectedExceptionMessage, and @expectedExceptionMessageRegExp annotations are deprecated. They will be removed in PHPUnit 9. Refactor your test to use expectException(), expectExceptionCode(), expectExceptionMessage(), or expectExceptionMessageRegExp() instead.
- [x] #32846 assertInternalType() is deprecated and will be removed in PHPUnit 9. Refactor your test to use assertIsArray(), assertIsBool(), assertIsFloat(), assertIsInt(), assertIsNumeric(), assertIsObject(), assertIsResource(), assertIsString(), assertIsScalar(), assertIsCallable(), or assertIsIterable() instead.
- [x] #32865 Declaration of ...::createMock($classname) must be compatible with PHPUnit\Framework\TestCase::createMock
- [x] #32854 add `void` return types on branch 4.3+ where setup/teardown methods are still used
- [x] https://github.com/php-cache/integration-tests/pull/102 do the same with 3rd party deps that we use

And fix PHP 7.4 deprecations:
- [x] #32981 Invalid characters passed for attempted conversion
- [x] #32981 Trying to access array offset on value of type [...]
- [x] #32981 array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead
- [x] #32992 Function ReflectionType::__toString() is deprecated
- [x] #32862 Uncaught TypeError: abs() expects parameter 1 to be int or float, string given
- [x] #32862 PHP-8: Uncaught TypeError: abs() expects parameter 1 to be int or float, string given
- [x] #32864 skip tests that are fatal on PHP 7.4 for now - we can work on them later
- [x] https://github.com/twigphp/Twig/pull/3097 fix using array_key_exists() on objects in Twig
- [x] https://github.com/doctrine/orm/pull/7785 https://github.com/doctrine/annotations/pull/258 Trying to access array offset on value of type [...]

Then:
- [x] #33000 same on 4.3
- [x] same on 4.4/master
- [ ] fix #32995

I'm opening this issue to ask for help to the community, this is a lot of work that can be split efficiently I believe.

**Comment by luispabon** [comment]
I can perhaps help with this.

**Comment by jderusse** [comment]
just posting a comment here in order to avoid that there are two of us working on the same thing:  I'm taking the deprecation `@expectedException*`

**Comment by luispabon** [comment]
I'm doing the void return declarations on `setUp*` and `tearDown*`

**Comment by nicolas-grekas** [comment]
Only #32995 remaining, we can close here. Thank you everyone involved.
