### ISSUE TITLE
[Meta] PHP 8.1 Support

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony#41552]
**Symfony version(s) affected**: 4.4, 5.3, 5.4, 6.0

## Description
In November, PHP 8.1 will be released and we should be prepared. In this PR, I'd like to track the efforts necessary to make all actively maintained branches ready for that release.

Ready means: if an application uses features of PHP 8.1, Symfony must not blow up.

We do already have a GitHub action that tests all branches with PHP 8.1. This action will always pass, but the output will show us if we're compatible yet: https://github.com/symfony/symfony/runs/2752054643

I will update this issue as we progress.

## How to Contribute

If you want to join the effort, please start with the components and bridges. Fixing those will also fix many broken bundle tests. Reminder: We treat compatibility issues as bugs. As always, please fix bugs on the lowest maintained branch that suffers from the bug.

### Components

- [x] Asset
    - [x] #41559
- [x] BrowserKit
- [x] Cache
    - [x] doctrine/dbal#4662
    - [x] predis/predis#706
    - [x] #42819
- [x] Config
    - [x] #43260
- [x] Console
    - [x] #41555
    - [x] Failing test: `ApplicationTest::testRenderExceptionWithDoubleWidthCharacters`
    - [x] Failing test: `Symfony\Component\Console\Tests\Style\SymfonyStyleTest::testOutputs`
- [x] CssSelector
- [x] Debug
- [ ] DependencyInjection
    - [x] #41592
    - [x] #41603
    - [x] laminas/laminas-code#86
    - [x] #43277
    - [ ] #44639
- [x] DomCrawler
    - [x] Masterminds/html5-php#207
- [x] Dotenv
- [x] ErrorHandler
    - [x] #42761
- [x] EventDispatcher
- [x] ExpressionLanguage
- [x] Filesystem
- [x] Finder
- [x] Form
    - [x] doctrine/collections#277
    - [x] Failing test: `NumberToLocalizedStringTransformerTest`
    - [x] #42630
- [x] HttpClient
    - [x] #41622
    - [x] #41624
    - [x] #42769
- [x] HttpFoundation
    - [x] #41626
    - [x] sebastianbergmann/type#15
    - [x] #41556
    - [x] Failing test: `BinaryFileResponseTest::testSetContentDispositionGeneratesSafeFallbackFilename`
    - [x] #42380
    - [x] #42783
    - [x] #43357
- [x] HttpKernel
    - [x] #42618
- [x] Inflector
- [x] Intl
- [x] Ldap
- [x] Lock
    - [x] doctrine/dbal#4662
    - [x] Failing test: SemaphoreStoreTest::testBlockingLocks
    - [x] #41555
    - [x] predis/predis#706
- [x] Mailer
- [x] Messenger
    - [x] doctrine/dbal#4662
    - [x] #41558
- [x] Mime
    - [x] #41614
- [x] Notifier
- [x] OptionsResolver
- [x] PasswordHasher
- [x] Process
- [x] PropertyAccess
- [x] PropertyInfo
- [x] RateLimiter
- [x] Routing
- [x] SecurityCore
    - [x] #41554
    - [x] #41567
- [x] SecurityCsrf
- [x] SecurityGuard
    - [x] #41554
- [x] SecurityHttp
    - [x] #41554
- [x] Serializer
    - [x] #41556
    - [x] #43062
- [x] Semaphore
- [x] Stopwatch
- [x] String
    - [x] #41561
- [x] Templating
- [x] Translation
    - [x] #41562
    - [x] Failing test: `PseudoLocalizationTranslatorTest::testTrans`
- [x] Uid
- [x] Validator
    - [x] #41636
- [x] VarDumper
    - [x] #41701
    - [x] #41555
    - [x] #43270
- [x] VarExporter
    - [x] #41627
    - [x] #42782
- [x] WebLink
- [x] Workflow
- [x] Yaml
    - [x] #41555

### Bridges

- [x] Doctrine
    - [x] doctrine/dbal#4662
    - [x] doctrine/dbal#4734
    - [x] doctrine/orm#8742
    - [x] doctrine/persistence#189
    - [x] doctrine/collections#277
- [x] Monolog
    - [x] Seldaek/monolog#1554
- [x] PhpUnit
- [x] ProxyManager
    - [x] laminas/laminas-code#86
- [x] Twig
    - [x] #41554

### Bundles

- [x] DebugBundle
- [x] FrameworkBundle
    - [x] #41565
    - [x] Masterminds/html5-php#207
    - [x] #41554
    - [x] #41557
    - [x] #42768
    - [x] #42835
- [x] SecurityBundle
    - [x] Masterminds/html5-php#207
    - [x] #41554
    - [x] #41557
    - [x] #42770
- [x] TwigBundle
    - [x] #41557
- [x] WebProfilerBundle
    - [x] Masterminds/html5-php#207
    - [x] #41565
    - [x] twigphp/Twig#3536
    - [x] #41557
- [x] WebServerBundle

**Comment by rvanlaak** [comment]
> ErrorHandler
>  Broken test: fatal_with_nested_handlers.phpt

Tried to start making fixes for PHP 8.1, but this test seems to fail locally on PHP 8.0.7 as well. 

Same for `Symfony\Component\ErrorHandler\Tests\DebugClassLoaderTest::testVirtualUse`, which seems to fail on the `:` return character:

![image](https://user-images.githubusercontent.com/2707563/124115602-4beccd00-da6e-11eb-998f-da4b734ec45b.png)


Is there anything in my run configuration why this could fail?

**Comment by alexpott** [comment]
Just opened #42074

**Comment by herndlm** [comment]
Started looking into the failing Console tests and noticed a behaviour difference in `mb_detect_decoding` that incorrectly detects UTF-8 as being ASCII in some cases which leads to converting UTF-8 to UTF-8 or incorrectly determing string lengths whichs breaks the formatting. Opened https://bugs.php.net/bug.php?id=81366 for that (my first ever PHP bug, please all be kind :))
UPDATE: was apparently a duplicate, see https://bugs.php.net/bug.php?id=81349 which will be fixed in the next beta which should fix
- `ApplicationTest::testRenderExceptionWithDoubleWidthCharacters`
- `Symfony\Component\Console\Tests\Style\SymfonyStyleTest::testOutputs`
- `PseudoLocalizationTranslatorTest`
- `NumberToLocalizedStringTransformerTest`
- `BinaryFileResponseTest::testSetContentDispositionGeneratesSafeFallbackFilename`

**Comment by derrabus** [comment]
Thank you for investigating, @herndlm! ❤️ 

edit: I've ticked off the tests you mentioned because they don't fail in our CI anymore.

**Comment by nicolas-grekas** [comment]
Task completed, kudos @derrabus! :muscle:

**Comment by derrabus** [comment]
Thanks everyone who helped with making Symfony ready for PHP 8.1! 🎉
