### ISSUE TITLE
[Meta] PHP 8.2 Support

### ISSUE THREAD

**Issue by derrabus** [symfony/symfony#44282]
### Symfony version(s) affected

(4.4), ~~5.3~~, 5.4, 6.0, 6.1, 6.2

### Description

In November 2022, PHP 8.2 will be released and we should be prepared. In this PR, I'd like to track the efforts necessary to make all actively maintained branches ready for that release.

Ready means: if an application uses features of PHP 8.2, Symfony must not blow up.

We do already have a GitHub action that tests all branches with PHP 8.2. This action will constantly monitor Symfony's compatibility with the current state of PHP 8.2.

I will update this issue as we progress.

### How to Contribute

If you want to join the effort, please start with the components and bridges. Fixing those will also fix many broken bundle tests. Reminder: We treat compatibility issues as bugs. As always, please fix bugs on the lowest maintained branch that suffers from the bug.

#### Components

- Asset
- BrowserKit
- Cache
    - [x] #43700
- Config
- Console
    - [x] #43700
- CssSelector
- Debug
- DependencyInjection
    - [x] `ContainerBuilderTest`, `PhpDumperTest`: Creation of dynamic property is deprecated
    - [x] #45532
    - [x] #46973
- DomCrawler
    - [x] #45532
- Dotenv
- ErrorHandler
- EventDispatcher
- ExpressionLanguage
- Filesystem
- Finder
- Form
- HttpClient
- HttpFoundation
- HttpKernel
    - [x] #44281
- Inflector
- Intl
- Ldap
- Lock
    - [x] Creation of dynamic property `DateTime::*` is deprecated
- Mailer
- Messenger
- Mime
- Notifier
- OptionsResolver
- PasswordHasher
- Process
- PropertyAccess
- PropertyInfo
    - [x] #46968
- RateLimiter
- Routing
- SecurityCore
- SecurityCsrf
- SecurityGuard
- SecurityHttp
- Serializer
    - [x] `ObjectNormalizerTest`: Creation of dynamic property is deprecated
    - [x] #45532
- Semaphore
- Stopwatch
- String
- Templating
- Translation
- Uid
- Validator
    - [x] #45532
- VarDumper
    - [x] #44281
    - [x] `CliDumperTest`, `HtmlDumperTest`, `SplCasterTest`: Creation of dynamic property is deprecated
    - [x] #45532
    - [x] #46967
- VarExporter
    - [x] `InstantiatorTest`, `VarExporterTest`: Creation of dynamic property is deprecated
    - [x] #45532
- WebLink
- Workflow
    - [x] Creation of dynamic property `Symfony\Component\Filesystem\Tests\Fixtures\MockStream\MockStream::$context` is deprecated
- Yaml

#### Bridges

- Doctrine
    - [x] `UniqueEntityValidatorTest`: Creation of dynamic property is deprecated
- Monolog
- PhpUnit
- ProxyManager
    - [x] `ProxyDumperTest`: Creation of dynamic property is deprecated
    - [x] #45532
- Twig
    - [x] #44281

#### Bundles

- DebugBundle
- FrameworkBundle
    - [x] #44281
    - [x] Creation of dynamic property `Doctrine\Common\Annotations\PsrCachedReader::$cacheProviderBackup` is deprecated
    - [x] #45532
    - [x] #46970
- SecurityBundle
- TwigBundle
- WebProfilerBundle
    - [x] #44281
    - [x] `ProfilerControllerTest`: Creation of dynamic property is deprecated
- WebServerBundle

**Comment by stof** [comment]
To me, this is too early to mark component as compatible in the check list. PHP itself has not done the changes for PHP 8.2, so what your checkbox means for now is compatibility with PHP 8.1 plus a few commits, not with PHP 8.2.

**Comment by derrabus** [comment]
We can always un-check components if a new change is introduced to PHP that breaks a component. We did so on #41552 all the time.

But we can turn all those checkboxes into bullet points if that makes the list less confusing.

**Comment by derrabus** [comment]
Here you go, no more component checkboxes.

**Comment by nicolas-grekas** [comment]
Fixed by https://github.com/symfony/symfony/pull/45532

**Comment by wouterj** [comment]
Shouldn't we always keep this meta task open, until PHP 8.2 is released?

**Comment by nicolas-grekas** [comment]
I'm closing here because keeping it open is not needed: 8.2 is frozen now so the target is known and achieved. We have a CI job that runs 8.2 and this proved useful to report/fix issues upstream.
